### ISSUE TITLE
CSS comments

### ISSUE THREAD

**Issue by martoio** [VICBAEZ/Tea-Cozy#2]
I like that you've added comments, but make sure your comments are not obtrusive. If you block out 5-6 lines of code just to make a comment that says "Header CSS", you are wasting a ton of space which makes things harder to read.
https://github.com/VICBAEZ/Tea-Cozy/blob/3a13378af00fd37121e0a577bff40553c13345a4/resources/css/style.css#L188-L215

Comments are good, but don't overdo them. Same things applies to white space.

**Comment by VICBAEZ** [comment]
Sorry! the huge comments were intended for me to remind the places where I was working on. I had the idea to delete the extra lines prior to releasing my last version. Unfortunately I forgot to do so. :(
