### ISSUE TITLE
Main container height

### ISSUE THREAD

**Issue by martoio** [VICBAEZ/Tea-Cozy#3]
You set this to 700px. Why?
https://github.com/VICBAEZ/Tea-Cozy/blob/3a13378af00fd37121e0a577bff40553c13345a4/resources/css/style.css#L83

![image](https://user-images.githubusercontent.com/8990516/31206828-5406f8a4-a948-11e7-8265-1ea8a35e6688.png)
Currently this is the height of the container, which means all the other elements are overflowing. There's no need to limit the main container to a specific height. It will be as big as it needs to be.

**Comment by VICBAEZ** [comment]
I was having some positioning problems and in a certain moment I figured out that fixing the height of the main container could help me to solve them. Now I understand your point. Thank You!
