### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [VICBAEZ/Tea-Cozy#4]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility
(You did it for the logo, make sure you do it for the other images too)
https://github.com/VICBAEZ/Tea-Cozy/blob/3a13378af00fd37121e0a577bff40553c13345a4/index.html#L42

**Comment by VICBAEZ** [comment]
I´ll sure do!
