### ISSUE TITLE
Summary: Exceeds expectations

### ISSUE THREAD

**Issue by martoio** [VICBAEZ/Tea-Cozy#6]
Good job on the project! I like that you kept the code clean, with the minor exception of the giant CSS comments. You match the spec and you don't have issues with your elements. Check out some of the previous issues and links on how to make the code even more professional!

As a challenge, you can research and implement media queries to make your page responsive for different devices. You should be able to take a crack at this and make it good! Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

Great job and keep up the good work!

**Comment by VICBAEZ** [comment]
Thanks!
